### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by mhetreramesh** [zaherg/laravel-dusk#1]
Hi, This container helps us for running dusk test in the pipeline. Thanks for the great work.

Do you have any plan to support `7.4`?

**Comment by zaherg** [comment]
Hey @mhetreramesh to be honest I don't have any plan yet to build an image for PHP 7.4

**Comment by zaherg** [comment]
Done, PHP 7.4 was pushed today ..

@mhetreramesh please check and test as I didn't have much time to do so.

**Comment by mhetreramesh** [comment]
That's cool! I'll try it out over the weekend.
